### ISSUE TITLE
Suggestion For Docs

### ISSUE THREAD

**Issue by tobiasschweizer** [comunica/validate-iri.js#15]
Hi @rubensworks,

Nice lib!

Two suggestions:
- Is this a closing backtick? https://github.com/comunica/validate-iri.js/blob/master/README.md#L31
- You write that `validateIri` "Will throw an error if the IRI is invalid.". But actually it *returns* an error. This confused me a bit.

But now it works as expected. Thx.!

**Comment by rubensworks** [comment]
> Is this a closing backtick? https://github.com/comunica/validate-iri.js/blob/master/README.md#L31

Ah yes, that's a typo.

> You write that validateIri "Will throw an error if the IRI is invalid.". But actually it returns an error. This confused me a bit.

The README was written before the implementation, that's probably why.

A PR with README fixes is definitely welcome! :-)

**Comment by tobiasschweizer** [comment]
Here you go: https://github.com/comunica/validate-iri.js/pull/16 

:-)
